# Site Settings
site:           ult
url:            http://localhost:4000
title:          Ult
description:    Ultimate Title Site
twitter:
  username:     showbobbies
  card:         summary
github:
  username:     zroxxah

permalink:      pretty

paginate:       1000
paginate_path:  "/page:num/"
baseurl:        ""
# Build Settings
compress_html:
  clippings:    all
  comments:     ["<!-- ", " -->"]

sass:
  sass_dir:     _sass
  style:        :compressed

plugins:
  - kramdown:
      input:    GFM
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output:     true
    permalink:  /:name
  posts:
    output:     true
    permalink:  /:year/:month/:day/:slug
  projects:
    output:     true
    permalink:  /projects/:slug

defaults:
  -
    scope:
      path:     ""
    values:
      layout:   "default"
  -
    scope:
      path:     ""
      type:     "pages"
    values:
      layout:   "page"
  -
    scope:
      path:     ""
      type:     "posts"
    values:
      layout:   "post"
  -
    scope:
      path:     ""
      type:     "projects"
    values:
      layout:   "project"

  - scope:
      path:     "assets/images"
    values:
      image:    true
